#!/bin/sh
python neighborhood/manage.py syncdb --settings=neighborhood.settings.prod --noinput
python mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static
python neighborhood/manage.py collectstatic --settings=neighborhood.settings.prod --noinput